CLASS zabs_print DEFINITION ABSTRACT
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  METHODS: WRITE_DATA ABSTRACT.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zabs_print IMPLEMENTATION.
ENDCLASS.
