CLASS zdata_from_db DEFINITION INHERITING FROM ZABS_DATA
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  METHODS: READ_DATA REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zdata_from_db IMPLEMENTATION.
METHOD read_data.
    WRITE: / 'Reading data from DB'.
  ENDMETHOD.                    "read_data
ENDCLASS.
