CLASS zprint_alv DEFINITION INHERITING FROM ZABS_PRINT
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  METHODS: WRITE_DATA REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zprint_alv IMPLEMENTATION.
METHOD write_data.
    WRITE: / 'Writing data into ALV'.
  ENDMETHOD.                    "write_data
ENDCLASS.
