CLASS zreport DEFINITION ABSTRACT
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
   METHODS: get_data ABSTRACT,
             print_data ABSTRACT.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zreport IMPLEMENTATION.
ENDCLASS.
